macro(RequiredPkg _name)
    pkg_search_module("${_name}" REQUIRED IMPORTED_TARGET ${ARGN})
endmacro()

macro(OptionalPkg _name _cdef)
    option("CoturnWith${_name}" "Pass -D{_cdef} if disabled")
    if(CoturnAutodetectOptionalPkgs)
        pkg_search_module("${_name}" IMPORTED_TARGET ${ARGN})
        if(TARGET PkgConfig::${_name})
            set("CoturnWith${_name}" TRUE)
        else()
            set("CoturnWith${_name}" FALSE)
            list(APPEND CoturnOptionalPkgsDefinitions "-D${_cdef}")
        endif()
    else()
        if(CoturnWith${_name})
            pkg_search_module("${_name}" REQUIRED IMPORTED_TARGET ${ARGN})
        else()
            list(APPEND CoturnOptionalPkgsDefinitions "-D${_cdef}")
        endif()
    endif()
endmacro()
